### ISSUE TITLE
Snowflake Array Type should convert to Python List

### ISSUE THREAD

**Issue by jkruzek** [feast-dev/feast#3222] opened 2022-09-15 16:27 UTC
**Is your feature request related to a problem? Please describe.**
When using Snowflake as an Offline store where certain Snowflake columns have the Snowflake type of `ARRAY` this currently fails and tells the user to cast the column to a `VARCHAR`. This makes working with these columns more difficult since 1. we hve to convert that column to a type that isn't really what it is in Snowflake and 2. we then get a string back from the feature store when what we really want is a Python list. 

**Describe the solution you'd like**
Snowflake Array types should map to a Python List type. 

**Describe alternatives you've considered**

**Additional context**
@sfc-gh-madkins

**Comment by sfc-gh-madkins** [comment] 2022-12-29 21:04
@jkruzek sorry for the delay on this. Snowflake currently does not support list data types. Snowflake Arrays, Variants, etc are "Schema-less" types, and so the only thing they can be returned as is VARCHAR. Snowflake is working on this support in 2023

**Comment by sfc-gh-madkins** [comment] 2022-12-29 21:06
@jkruzek closing this out as the issue is created here: https://github.com/feast-dev/feast/issues/2280

**Closed by sfc-gh-madkins** 2022-12-29 21:06 UTC
Labels: kind/feature
