### ISSUE TITLE
Optimize DynamoDB Online Store method online_read

### ISSUE THREAD

**Issue by TremaMiguel** [feast-dev/feast#2351] opened 2022-03-02 00:44 UTC
**Is your feature request related to a problem? Please describe.**

DynamoDB Online Store method [online_read](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/online_stores/dynamodb.py#L185) process `entity_key` information [one at a time](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/online_stores/dynamodb.py#L208).

**Describe the solution you'd like**

There are two alternatives to consider to fetch items in parallel:

* Use Multiprocessing [Example from SageMaker SDK](https://github.com/aws/sagemaker-python-sdk/blob/26b984a2d693f95957e8555f19fa47aa36d5d5ea/src/sagemaker/feature_store/feature_group.py#L314)
* Use Multithreading. [Example from SageMaker SDK](https://github.com/aws/sagemaker-python-sdk/blob/26b984a2d693f95957e8555f19fa47aa36d5d5ea/src/sagemaker/feature_store/feature_group.py#L271)

**Comment by pyalex** [comment] 2022-03-02 19:44
Hi @TremaMiguel , thanks for reporting this issue. We're currently reworking the serving part and as part of this more efficient version (including DynamoDB) will be released. See #2339 for more details.

**Comment by TremaMiguel** [comment] 2022-03-04 23:23
@pyalex thanks for the ping on this I was not aware of it. I'm not familiar with Go, do you consider there's room to develop this one #2351 and #2247?

**Comment by adchia** [comment] 2022-03-04 23:27
I think this is a dupe of the other bug btw. But yes definitely open to contribution here!

**Closed by adchia** 2022-03-04 23:27 UTC
Labels: priority/p2, area/serving, kind/techdebt
