### ISSUE TITLE
Cannot start feast go server with helm

### ISSUE THREAD

**Issue by efenzha** [feast-dev/feast#3488] opened 2023-02-10 14:48 UTC
## Expected Behavior 
A go feature-server can be running.

## Current Behavior
Only a python feature-server is running

_INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:6566 (Press CTRL+C to quit)_

## Steps to reproduce
1. setting go_feature_serving: True in a feature_store.yaml
2. following [this guide](https://github.com/feast-dev/feast/tree/master/infra/charts/feast-feature-server) to install feature-server with helm.

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution
Adding a more clear guide about how to start go feature-server in readme.

**Comment by xyangShen** [comment] 2023-06-07 21:15
Same issue here, looking forward to solutions : ((

**Comment by TheFallen312** [comment] 2024-01-11 15:58
Have you found a solution? Encountered an issue myself. Go feature serving doesn't work for me with helm or just by using CLI with go_feature_serving: True in feature_store.yaml . If someone found a solution - please comment it here.

**Comment by peter-resnick** [comment] 2024-03-07 17:26
I am fairly certain that Feast no longer supports Go Servers and they just haven't updated the documentation - the source code doesnt allow for grpc type servers, even if you explicitly set it as such. It seems like an oversight on the documentation/code sync. Super disappointing as it is something I intended to use as well - especially since the docs point to it.

**Comment by jeremyary** [comment] 2024-03-07 17:52
@TheFallen312 @peter-resnick heya, we've recently given this another look as I've been working through issue backlogs & I can confirm that as of today (we're actually conversing on it in our Slack), there's a good amount of code in-repo for go feature server, but it currently is not executable due to falling out of maintenance some time ago. With new maintainers & revived interest in place, we're looking at a short-term update to docs to better inform users as to current condition, but I also hope long-term I to spur some discussions & activity for bringing the go server back into the fold. 

FWIW, a few weeks ago we had someone join our community [call](https://calendar.google.com/calendar/u/0?cid=ZTFsZHVhdGM3MDU3YTJucTBwMzNqNW5rajBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) & share that their company had been working with it out of a fork & would look to contribute back, so we're also hopeful we'll maybe see a jump start contribution in that direction soon.

**Comment by jeremyary** [comment] 2024-03-07 17:55
Going to close this issue and use your newly created [3998](https://github.com/feast-dev/feast/issues/3998) as a tracker given the bettter amount of info provided (and honestly, just time relevance). Thanks for opening, we'll bring updates there as we have them.

**Closed by jeremyary** 2024-03-07 17:55 UTC
Labels: kind/bug, priority/p2
