### ISSUE TITLE
feast teardown does not remove register.db

### ISSUE THREAD

**Issue by dmatrix** [feast-dev/feast#1747] opened 2021-07-29 19:18 UTC
## Expected Behavior 

`feast teardown`, with the respective provider, should remove both the online store and registery.db.

## Current Behavior

Apparantly, for local provider, it does not remove `registry.db`

## Steps to reproduce
Follow the Getting started tutorial. As a last step, after `feast materialize-incremental`, try `feast teardown`.

## Possible Solution

The code [seems to unlink](https://github.com/feast-dev/feast/blob/2dfdace8f8058aa76586c53ae19e394e669ed3c5/sdk/python/feast/registry.py#L596) the file, but not sure if the `_filepath` is the correct one. If incorrect, it'll raise `FileNotFoundError` exception and just pass.

It seems odd that feast creates the registry.db correctly, passed on as path in `feast_store.yaml` but fails to delete it.

**Comment by achals** [comment] 2021-07-29 20:37
You're right, the teardown command should be tearing down the registry as well.

**Comment by felixwang9817** [comment] 2021-07-29 23:28
Hm, I believe that `Path.unlink` actually removes the file; see [here](https://docs.python.org/3/library/pathlib.html#pathlib.Path.unlink) and [here](https://www.jquery-az.com/python-delete-file-directory-os-pathlib-shutil/). I think the issue is that the PR that introduced registry teardown (#1718) was quite recent, and hasn't been released yet; I suspect this issue should vanish in the new release.

**Comment by achals** [comment] 2021-07-29 23:38
Oh boom. We should close this out after the next release.

**Comment by dmatrix** [comment] 2021-07-30 03:54
Brilliant!

**Closed** 2021-08-10 16:31 UTC
Labels: good first issue, kind/bug, area/sdks
