### ISSUE TITLE
Solve feast conflict dependencies for [gcp]

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#1912] opened 2021-09-29 19:07 UTC
## Expected Behavior 
`pip-compile` should run without error and result in a nice lock files of the libraries to install

## Current Behavior
`pip-compile` will find conflict in the current feast[gcp] dependencies. Did not try for [aws] or [redis]
<img width="1774" alt="image" src="https://user-images.githubusercontent.com/18557047/135331637-5c3d47ad-ebe0-4a27-b335-93617675027f.png">

## Steps to reproduce
```bash
echo "-e  sdk/python[gcp]" > sdk/python/requirements.txt
pip-compile --dry-run sdk/python/requirements.txt
```
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/18557047/135332916-c368ca80-3276-40ab-a3bd-42c48d52c2e9.png">

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by MattDelac** [comment] 2021-11-02 20:08
Indeed I also have some issues with protobuf
![image](https://user-images.githubusercontent.com/18557047/139944640-c685cd17-26ec-402b-99d7-978c3bd1de61.png)

**Comment by ysk24ok** [comment] 2021-11-03 02:56
#1992 will solve the problem written in https://github.com/feast-dev/feast/issues/1912#issuecomment-958128523.

I've found out the reason why the problem written in https://github.com/feast-dev/feast/issues/1912#issuecomment-957355854 still happens.
In [the v0.14.1 tarball uploaded to PyPI](https://files.pythonhosted.org/packages/c2/8e/46a92e722ac45fd883aaddcd6c3345c89ce45caf000c778a70e79c3431ca/feast-0.14.1.tar.gz) , `setup.py` still shows `google-cloud-storage>=1.34.*"` which doesn't include `<1.41` specification added by #1955. That means #1955 is not included in v1.14.1 ...

**Comment by ysk24ok** [comment] 2021-11-03 06:00
Users who use pipenv or pip-compile and suffer from installing `feast[gcp]` can use poetry.

```console
$ cat pyproject.toml
[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
authors = ["Yusuke Nishioka <yusuke.nishioka.0713@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
feast = {extras = ["gcp"], version = "^0.14.1"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
$ poetry install
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

Package operations: 56 installs, 2 updates, 1 removal

  • Removing platformdirs (2.4.0)
  • Installing pyasn1 (0.4.8)
  • Installing cachetools (4.2.4)
  • Installing protobuf (3.17.3)
  • Installing pyasn1-modules (0.2.8)
  • Updating pyparsing (3.0.4 -> 2.4.7)
  • Installing rsa (4.7.2)
  • Installing google-auth (1.35.0)
  • Installing googleapis-common-protos (1.52.0)
  • Installing mypy-extensions (0.4.3)
  • Updating packaging (20.9 -> 21.2)
  • Installing pytz (2021.3)
  • Installing sniffio (1.2.0)
  • Installing typing-extensions (3.10.0.2)
  • Installing anyio (3.3.4)
  • Installing google-api-core (1.31.3)
  • Installing google-crc32c (1.3.0)
  • Installing grpcio (1.41.1)
  • Installing numpy (1.21.3)
  • Installing python-dateutil (2.8.2)
  • Installing pyyaml (6.0)
  • Installing typing-inspect (0.7.1)
  • Installing asgiref (3.4.1)
  • Installing attrs (21.2.0)
  • Installing click (7.1.2)
  • Installing fastavro (1.4.7)
  • Installing google-cloud-core (1.4.4)
  • Installing google-resumable-media (1.3.3)
  • Installing h11 (0.12.0)
  • Installing httptools (0.2.0)
  • Installing libcst (0.3.21)
  • Installing markupsafe (2.0.1)
  • Installing pandas (1.3.4)
  • Installing proto-plus (1.19.6)
  • Installing pydantic (1.8.2)
  • Installing pyrsistent (0.18.0)
  • Installing python-dotenv (0.19.1)
  • Installing starlette (0.16.0)
  • Installing uvloop (0.16.0)
  • Installing watchgod (0.7)
  • Installing websockets (10.0)
  • Installing colorama (0.4.4)
  • Installing dill (0.3.4)
  • Installing fastapi (0.70.0)
  • Installing google-cloud-bigquery (2.29.0)
  • Installing google-cloud-bigquery-storage (2.9.1)
  • Installing google-cloud-datastore (2.3.0)
  • Installing google-cloud-storage (1.40.0)
  • Installing jinja2 (3.0.2)
  • Installing jsonschema (4.1.2)
  • Installing mmh3 (3.0.0)
  • Installing pandavro (1.5.2)
  • Installing pyarrow (6.0.0)
  • Installing tabulate (0.8.9)
  • Installing tenacity (8.0.1)
  • Installing toml (0.10.2)
  • Installing tqdm (4.62.3)
  • Installing uvicorn (0.15.0)
  • Installing feast (0.14.1)
```

`google-cloud-storage==1.40.0` and `proto-plus==1.19.6` are installed, which #1955 and #1992 aimed respectively.
Dependency resolver of poetry is quite smart.

**Comment by ysk24ok** [comment] 2021-11-10 08:25
Now we can install `feast[gcp]==0.15.0` via pipenv (not confirmed with pip-compile).
Is it a good time to close this issue?

**Comment by MattDelac** [comment] 2021-11-10 17:56
> Now we can install `feast[gcp]==0.15.0` via pipenv

But does that mean that there is still no conflict dependencies when trying things like `pip-compile --dry-run` ?

**Comment by adchia** [comment] 2021-11-22 19:32
Quick followup on whether this is temporarily resolved or not?

**Comment by ysk24ok** [comment] 2021-11-23 07:40
> But does that mean that there is still no conflict dependencies when trying things like `pip-compile --dry-run` ?

Yes, I guess so.

```console
$ cat requirements.in
feast[gcp]
$ pip-compile --dry-run requirements.in
...
feast[gcp]==0.15.1
    # via -r requirements.in
...
Dry-run, so nothing updated.
```

> Quick followup on whether this is temporarily resolved or not?

Yes, It seems solved temporarily.
But if a package which feast depends on updates its dependencies (e.g. using newer versions of the dependency) and it conflicts with that of feast, this problem happens again.
To fix this completely. we need a lock mechanism provided by e.g. pipenv, pip-compile or poetry. which is proposed in #1993.

**Comment by ysk24ok** [comment] 2021-12-08 11:46
Now that #2093 is merged, `requirements.txt` created by `pip-compile` is used to install dependencies.
But I've noticed that this isn't enough because users who run `pipenv` or `pip-compile`  to install Feast install dependencies based on `setup.py`, not `requirements.txt`.
If `requirements.txt` gets old, they might encounter the same problem.
To solve this, maintainers (or CI?) have to update `requirements.txt` regularly.

**Closed** 2022-01-05 04:58 UTC
Labels: kind/bug, priority/p0
