### ISSUE TITLE
feast materialize fails while sending larger dataset to Datastore as online store

### ISSUE THREAD

**Issue by aqibfayyaz** [feast-dev/feast#2027] opened 2021-11-12 07:27 UTC
Hi,  i am using bigquery as datasource and Datastore as online store and when i run the command
**fs.materialize**
it sends half the the records to online store and after that it throws the following error
_**InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "The referenced transaction has expired or is no longer valid."
	debug_error_string = "{"created":"@1636535871.261130485","description":"Error received from peer ,"file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"The referenced transaction has expired or is no longer valid.","grpc_status":3}"
InvalidArgument: 400 The referenced transaction has expired or is no longer valid.**
i have 5119 rows and if i get online features i can get 3400 records above it i get none values for all the rows.

**Comment by achals** [comment] 2021-11-12 18:17
Hey @aqibfayyaz , can you please also provide the full stack trace of the error along with what version of feast you're using?

**Comment by felixwang9817** [comment] 2021-11-12 18:49
Note this is a duplicate of a [conversation](https://tectonfeast.slack.com/archives/C01MSKCMB37/p1636542279120000) happening on Slack.

**Comment by adchia** [comment] 2022-04-21 21:30
Consolidating in the linked issue

**Closed by adchia** 2022-04-21 21:30 UTC
Labels: kind/bug, priority/p1
