### ISSUE TITLE
feature-server-java 0.17.0 not work

### ISSUE THREAD

**Issue by hsz1273327** [feast-dev/feast#2195] opened 2022-01-06 03:36 UTC
### Specifications

- Version: 0.17.0
- Platform: docker

here is the compose:

```docker-compose
...
services:
  ...
  feature-grpc:
    command:
      - java
      - -Xms1g
      - -Xmx4g
      - -jar
      - /opt/feast/feast-serving.jar
      - /etc/feast/application.yml
    configs:
    - source: feast_serve_conf
      target: /etc/feast/application.yml
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 100s

...
```

here is the log:

```txt
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:


1) [Guice/MissingImplementation]: No implementation for Server was bound.


Learn more:

  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION


1 error


======================

Full classname legend:

======================

Server: "io.grpc.Server"

========================

End of classname legend:

========================


	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1126)

	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1086)

	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)

```

and please write a document for the image [feastdev/feature-server-java](https://hub.docker.com/r/feastdev/feature-server-java). Or if feature-server-java is not ready,please show it in the project's readme, set it as a preview feature first.
![截屏2022-01-06 上午11 30 03](https://user-images.githubusercontent.com/7850148/148323870-9af6e4d5-e566-4387-9156-d9afd683d714.png)

**Comment by adchia** [comment] 2022-01-06 18:44
Thanks for the issue! The issue you're seeing looks like it might be a regression that was introduced in 0.17 after a PR that removed spring boot in favor of Guice. There def is a module providing that though (https://github.com/feast-dev/feast/blob/master/java/serving/src/main/java/feast/serving/config/ServerModule.java#L41-L41) so hopefully should be a quick fix cc @achals 

Writing a document on using the java feature server is something we want to get done in the next 2 weeks, so stay tuned for that!

**Comment by pyalex** [comment] 2022-01-06 19:04
Hi @hsz1273327! Unfortunately, this issue slipped into the release, but it was already fixed in master. You can use dev image available here `gcr.io/kf-feast/feature-server-java:develop`

**Comment by pyalex** [comment] 2022-01-06 19:06
For reference: #2187

**Closed** 2022-01-06 19:05 UTC
Labels: priority/p1

**Comment by hsz1273327** [comment] 2022-01-07 02:38
thanks~
